# Be sure not to use commas - YAML doesn't use them.
# They'll get merged into the strings and cause weird issues.

displayName: Collate Example Mod Yaml
author: ppeb
version: 2.0.0
homepage: https://github.com/rejuvena/collate

side: Both
sortBefore: SomeModToSortBefore
sortAfter: SomeModToSortAfter

hideCode: false
hidResources: false
includeSource: true

buildIgnore: .collate/,Properties/,.accesstransformer,build.js
