using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Microsoft.Build.Framework;
using Mono.Cecil;
using Rejuevna.Collate.AccessTransformer;
using Rejuvena.Collate.Util.Cecil;
using Rejuvena.Collate.Util.Cecil.Resolvers;
using BuildTask = Microsoft.Build.Utilities.Task;

namespace Rejuvena.Collate.Features.AssemblyReferenceModification
{
    public sealed class ModifyAssemblyReferencesTask : BuildTask
    {
        [Required]
        public string AccessTransformerPaths { get; set; } = "";

        // [Required]
        [Obsolete("Use AccessTransformerPaths")]
        public string AccessTransformerPath { get; set; } = "";

        [Required]
        public string ProjectDirectory { get; set; } = "";

        [Required]
        public string References { get; set; } = "";

        [Output]
        public string[] ReferencesToRemove { get; set; } = Array.Empty<string>();

        [Output]
        public string[] ReferencesToAdd { get; set; } = Array.Empty<string>();

        public string CollateDir => Path.Combine(ProjectDirectory, ".collate");

        public string LibDir => Path.Combine(CollateDir, "lib");

        public override bool Execute() {
            if (Directory.Exists(LibDir)) Directory.Delete(LibDir, true);
            Directory.CreateDirectory(LibDir);

            List<string> referenceFiles = References.Split(';').ToList();
            List<(string original, string transformed)> cachedReferences = new();

            AccessTransformerPaths = AccessTransformerPaths.Trim().Trim(';');

#pragma warning disable CS0618
            if (!string.IsNullOrEmpty(AccessTransformerPath) && File.Exists(AccessTransformerPath)) AccessTransformerPaths += ';' + AccessTransformerPath;
#pragma warning restore CS0618

            string[] atPaths = AccessTransformerPaths.Split(';');
            List<IAtFile> atFiles = atPaths
                                   .Where(LogFileExists)
                                   .Select(AtFileFactory.CreateFromFile)
                                   .ToList();

            foreach (string file in referenceFiles) {
                Log.LogMessage("Preparing to transform assembly: " + file);

                bool modified = false;
                string libPath = Path.GetDirectoryName(referenceFiles.First(x => x.EndsWith("tModLoader.dll")))!;
                ModuleDefinition module = ModuleFactory.CreateModuleFromFile(file, new TerrariaAssemblyResolver(Log, Path.Combine(libPath, "Libraries")));

                foreach (IAtFile atFile in atFiles) modified |= atFile.Transform(module);

                if (!modified) {
                    module.Dispose();
                    Log.LogMessage($"No modifications were made to the assembly at \"{file}\", skipping.");
                }
                else {
                    string resultingDir = Path.Combine(LibDir, Path.GetFileName(file));
                    Log.LogMessage($"Modifications were made to \"{file}\", writing to \"{resultingDir}\"...");

                    using MemoryStream dllMem = new();
                    module.Write(dllMem);
                    module.Dispose();
                    File.WriteAllBytes(resultingDir, dllMem.ToArray());
                    cachedReferences.Add((original: file, transformed: resultingDir));
                }
            }

            /*StringBuilder sb = new();
            sb.AppendLine("<Project>");

            sb.AppendLine("    <!-- This file is automatically generated, changes will be overridden upon compilation. -->");

            sb.AppendLine("    <ItemGroup>");
            foreach (string reference in cachedReferences.Select(x => x.original)) sb.AppendLine($"        <Reference Remove=\"{reference}\" />");
            sb.AppendLine("    </ItemGroup>");

            sb.AppendLine("    <ItemGroup>");
            foreach (string reference in cachedReferences.Select(x => x.transformed)) sb.AppendLine($"        <Reference Include=\"{reference}\" />");
            sb.AppendLine("    </ItemGroup>");

            sb.AppendLine("</Project>");

            File.WriteAllText(TargetsPath, sb.ToString());*/

            ReferencesToRemove = cachedReferences.Select(x => x.original).ToArray();
            ReferencesToAdd = cachedReferences.Select(x => x.transformed).ToArray();
            return true;
        }

        private bool LogFileExists(string file) {
            if (File.Exists(file)) {
                Log.LogMessage("Found access transformer file at: " + file);
                return true;
            }

            Log.LogMessage("Could not find access transformer file at: " + file);
            return false;
        }
    }
}