displayName: Collate DevTools
author: Tomat & ppeb
version: 1.0.0.0
homepage: https://github.com/rejuvena/collate

side: Client

hideCode: false
hidResources: false
includeSource: true

buildIgnore: .collate/,Properties/,.accesstransformer,build.yaml
